# Get all the poses after global optimization, in event of a loop closure

# Max number of poses to query 
int32 max_count
---
# Result
# indicate successful run of the service
bool success

# List of optimized poses
geometry_msgs/PoseStamped[] poses
